// Copyright 2012-2017 The CRAVE developers, University of Bremen, Germany. All rights reserved.
#pragma once

#include <string>

namespace crave {

class Constant;

/**
 * Base class to assign values generated by backend solvers to frontend variables
 */
struct AssignResult {
  /**
   * constructor
   */
  AssignResult() {}

  /**
   * destructor
   */
  virtual ~AssignResult() {}

  /**
   * Set the contained value to the value captured by the parameter
   * @param result
   */
  virtual void set_value(std::string const& result) = 0;

  /**
   * Convert the value captured by the parameter to an instance of Constant
   * @param result
   * @return an instance of Constant
   */
  virtual Constant to_constant(std::string const& result) const = 0;

  /**
   * Convert the contained value to an instance of Constant
   * @return an instance of Constant
   */
  virtual Constant value_as_constant() const = 0;
};
} /* namespace crave */
