#!/bin/bash

base_dir=$( cd $(dirname $0) && pwd )
source $base_dir/common.sh

if [ $# -lt 2 ]; then
  echo "usage: $0 <target_dir> package {package ...}"
  exit 21
fi

build="$1"
shift;

mkdir -p "$build"

for p in $@; do
  run_scripts download_unpack pre_build
done
