get_filename_component(Boolector_DIR ${CMAKE_CURRENT_LIST_FILE} PATH)
set(Boolector_BIN_DIRS     ${Boolector_DIR}/bin )
set(Boolector_INCLUDE_DIRS ${Boolector_DIR}/include/boolector )
set(Boolector_INCLUDE_DIR  ${Boolector_INCLUDE_DIRS} )
set(Boolector_LIBRARIES    ${Boolector_DIR}/lib/libboolector.a ${Boolector_DIR}/lib/libbtor2parser.a ${Boolector_DIR}/lib/libcadical.a ${Boolector_DIR}/lib/liblgl.a)
set(Boolector_VERSION 3.0.0)
